# Application
CAT_ID: GYXCt5ZCFAKETdDGhi3e
CAT_NAME: Bear
# CAT_ID: PiDDDeFAKEGwRty3HJ7N
# CAT_NAME: Nara

# Firestore
GOOGLE_FIREBASE_CREDENTIAL_FILE: google_firebase_creds.json
GOOGLE_FIRESTORE_COLLECTION_SOURCE: test
GOOGLE_FIRESTORE_COLLECTION_DESTINATION: litterTrips
